import { Food } from "./types";

export const foods: Food[] = [
  // Fruits (20)
  { id: "banana", name: "Banana", emoji: "🍌", category: "fruits" },
  { id: "avocado", name: "Avocado", emoji: "🥑", category: "fruits" },
  { id: "apple", name: "Apple", emoji: "🍎", category: "fruits" },
  { id: "pear", name: "Pear", emoji: "🍐", category: "fruits" },
  { id: "mango", name: "Mango", emoji: "🥭", category: "fruits" },
  { id: "peach", name: "Peach", emoji: "🍑", category: "fruits" },
  { id: "plum", name: "Plum", emoji: "🫐", category: "fruits" },
  { id: "blueberry", name: "Blueberry", emoji: "🫐", category: "fruits" },
  { id: "strawberry", name: "Strawberry", emoji: "🍓", category: "fruits" },
  { id: "raspberry", name: "Raspberry", emoji: "🍇", category: "fruits" },
  { id: "watermelon", name: "Watermelon", emoji: "🍉", category: "fruits" },
  { id: "cantaloupe", name: "Cantaloupe", emoji: "🍈", category: "fruits" },
  { id: "papaya", name: "Papaya", emoji: "🥝", category: "fruits" },
  { id: "kiwi", name: "Kiwi", emoji: "🥝", category: "fruits" },
  { id: "apricot", name: "Apricot", emoji: "🍑", category: "fruits" },
  { id: "cherry", name: "Cherry", emoji: "🍒", category: "fruits" },
  { id: "grape", name: "Grape", emoji: "🍇", category: "fruits" },
  { id: "fig", name: "Fig", emoji: "🫒", category: "fruits" },
  { id: "date", name: "Date", emoji: "🌴", category: "fruits" },
  { id: "prune", name: "Prune", emoji: "🟣", category: "fruits" },
  // Vegetables (25)
  { id: "sweet-potato", name: "Sweet Potato", emoji: "🍠", category: "vegetables" },
  { id: "carrot", name: "Carrot", emoji: "🥕", category: "vegetables" },
  { id: "pea", name: "Peas", emoji: "🟢", category: "vegetables" },
  { id: "green-bean", name: "Green Beans", emoji: "🫛", category: "vegetables" },
  { id: "butternut-squash", name: "Butternut Squash", emoji: "🎃", category: "vegetables" },
  { id: "zucchini", name: "Zucchini", emoji: "🥒", category: "vegetables" },
  { id: "broccoli", name: "Broccoli", emoji: "🥦", category: "vegetables" },
  { id: "cauliflower", name: "Cauliflower", emoji: "🤍", category: "vegetables" },
  { id: "spinach", name: "Spinach", emoji: "🥬", category: "vegetables" },
  { id: "kale", name: "Kale", emoji: "🥬", category: "vegetables" },
  { id: "pumpkin", name: "Pumpkin", emoji: "🎃", category: "vegetables" },
  { id: "beet", name: "Beet", emoji: "🟤", category: "vegetables" },
  { id: "corn", name: "Corn", emoji: "🌽", category: "vegetables" },
  { id: "potato", name: "Potato", emoji: "🥔", category: "vegetables" },
  { id: "parsnip", name: "Parsnip", emoji: "🥕", category: "vegetables" },
  { id: "turnip", name: "Turnip", emoji: "🫜", category: "vegetables" },
  { id: "asparagus", name: "Asparagus", emoji: "🌿", category: "vegetables" },
  { id: "bell-pepper", name: "Bell Pepper", emoji: "🫑", category: "vegetables" },
  { id: "cucumber", name: "Cucumber", emoji: "🥒", category: "vegetables" },
  { id: "tomato", name: "Tomato", emoji: "🍅", category: "vegetables" },
  { id: "eggplant", name: "Eggplant", emoji: "🍆", category: "vegetables" },
  { id: "mushroom", name: "Mushroom", emoji: "🍄", category: "vegetables" },
  { id: "celery", name: "Celery", emoji: "🥬", category: "vegetables" },
  { id: "leek", name: "Leek", emoji: "🧅", category: "vegetables" },
  { id: "artichoke", name: "Artichoke", emoji: "🌻", category: "vegetables" },
  // Grains & Starches (15)
  { id: "rice", name: "Rice", emoji: "🍚", category: "grains" },
  { id: "oatmeal", name: "Oatmeal", emoji: "🥣", category: "grains" },
  { id: "pasta", name: "Pasta", emoji: "🍝", category: "grains" },
  { id: "bread", name: "Bread", emoji: "🍞", category: "grains" },
  { id: "quinoa", name: "Quinoa", emoji: "🌾", category: "grains" },
  { id: "barley", name: "Barley", emoji: "🌾", category: "grains" },
  { id: "millet", name: "Millet", emoji: "🌾", category: "grains" },
  { id: "couscous", name: "Couscous", emoji: "🥘", category: "grains" },
  { id: "polenta", name: "Polenta", emoji: "🟡", category: "grains" },
  { id: "pancake", name: "Pancake", emoji: "🥞", category: "grains" },
  { id: "tortilla", name: "Tortilla", emoji: "🫓", category: "grains" },
  { id: "pita", name: "Pita", emoji: "🫓", category: "grains" },
  { id: "cracker", name: "Cracker", emoji: "🍘", category: "grains" },
  { id: "cereal", name: "Baby Cereal", emoji: "🥣", category: "grains" },
  { id: "noodles", name: "Noodles", emoji: "🍜", category: "grains" },
  // Proteins (25)
  { id: "chicken", name: "Chicken", emoji: "🍗", category: "proteins" },
  { id: "turkey", name: "Turkey", emoji: "🦃", category: "proteins" },
  { id: "beef", name: "Beef", emoji: "🥩", category: "proteins" },
  { id: "lamb", name: "Lamb", emoji: "🐑", category: "proteins" },
  { id: "pork", name: "Pork", emoji: "🥓", category: "proteins" },
  { id: "salmon", name: "Salmon", emoji: "🐟", category: "proteins" },
  { id: "cod", name: "Cod", emoji: "🐟", category: "proteins" },
  { id: "tuna", name: "Tuna", emoji: "🐠", category: "proteins" },
  { id: "sardine", name: "Sardine", emoji: "🐟", category: "proteins" },
  { id: "shrimp", name: "Shrimp", emoji: "🦐", category: "proteins" },
  { id: "egg", name: "Egg", emoji: "🥚", category: "proteins" },
  { id: "tofu", name: "Tofu", emoji: "🧈", category: "proteins" },
  { id: "lentils", name: "Lentils", emoji: "🫘", category: "proteins" },
  { id: "chickpea", name: "Chickpeas", emoji: "🫘", category: "proteins" },
  { id: "black-bean", name: "Black Beans", emoji: "🫘", category: "proteins" },
  { id: "kidney-bean", name: "Kidney Beans", emoji: "🫘", category: "proteins" },
  { id: "white-bean", name: "White Beans", emoji: "🫘", category: "proteins" },
  { id: "peanut-butter", name: "Peanut Butter", emoji: "🥜", category: "proteins" },
  { id: "almond-butter", name: "Almond Butter", emoji: "🌰", category: "proteins" },
  { id: "tahini", name: "Tahini", emoji: "🫙", category: "proteins" },
  { id: "hummus", name: "Hummus", emoji: "🫕", category: "proteins" },
  { id: "tempeh", name: "Tempeh", emoji: "🟫", category: "proteins" },
  { id: "liver", name: "Liver", emoji: "🫀", category: "proteins" },
  { id: "bone-broth", name: "Bone Broth", emoji: "🍲", category: "proteins" },
  { id: "edamame", name: "Edamame", emoji: "🫛", category: "proteins" },
  // Dairy & Other (15)
  { id: "yogurt", name: "Yogurt", emoji: "🥛", category: "dairy" },
  { id: "cheese", name: "Cheese", emoji: "🧀", category: "dairy" },
  { id: "cottage-cheese", name: "Cottage Cheese", emoji: "🧀", category: "dairy" },
  { id: "ricotta", name: "Ricotta", emoji: "🤍", category: "dairy" },
  { id: "butter", name: "Butter", emoji: "🧈", category: "dairy" },
  { id: "cream-cheese", name: "Cream Cheese", emoji: "🧀", category: "dairy" },
  { id: "coconut", name: "Coconut", emoji: "🥥", category: "other" },
  { id: "olive-oil", name: "Olive Oil", emoji: "🫒", category: "other" },
  { id: "cinnamon", name: "Cinnamon", emoji: "🟤", category: "other" },
  { id: "cumin", name: "Cumin", emoji: "🌿", category: "other" },
  { id: "turmeric", name: "Turmeric", emoji: "🟡", category: "other" },
  { id: "basil", name: "Basil", emoji: "🌿", category: "other" },
  { id: "oregano", name: "Oregano", emoji: "🌿", category: "other" },
  { id: "garlic", name: "Garlic", emoji: "🧄", category: "other" },
  { id: "ginger", name: "Ginger", emoji: "🫚", category: "other" },
];

export const categoryLabels: Record<string, string> = {
  fruits: "Fruits",
  vegetables: "Vegetables",
  grains: "Grains & Starches",
  proteins: "Proteins",
  dairy: "Dairy",
  other: "Herbs, Spices & Oils",
};

export const categoryOrder: string[] = [
  "fruits",
  "vegetables",
  "grains",
  "proteins",
  "dairy",
  "other",
];

export function getFoodById(id: string): Food | undefined {
  return foods.find((f) => f.id === id);
}
